name: Display Email Step

on:
  workflow_dispatch:  # Allows manual triggering from GitHub UI

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: 22f3002394@ds.study.iitm.ac.in
        run: echo "Hello, world! This step includes the email."
